In [1]:
from scipy import stats
import numpy as np

In [2]:
matrix = np.array([[8,0,3,4,6], [5,6,1,8,9], [8,0,0,5,10]])

novoUser = [8,0,2,3,0]
nao_assistidos = [0,1,0,0,1]

nome_filmes = ['Round 6','A Invocação do Mal','9 Desconhecidos', 'You', 'La Casa de Papel']

print(matrix)

[[ 8  0  3  4  6]
 [ 5  6  1  8  9]
 [ 8  0  0  5 10]]


In [3]:
similarity = [0] * 3
print(similarity)

[0, 0, 0]


In [17]:
#criando um vetor com 3 posições e preencher com zero (vamos colocar os valores da similaridade entre o novoUser e cada outro usuário da matriz )
similarity =[0] * 3

#para cada usuário no sistema...
for i in range(0,3):
  #para verificar o processo
  print('user:', i)

  #vamos pegar os dados desse usuário
  temp = matrix[i,:]

  print(f'Dados do usuário: {temp}')

  #MAS QUEREMOS APENAS COMPARAR OS DADOS QUE O NOVO USER ASSISTIU (OU SEJA... QUE NOVOUSER != 0)
  tempUser= [t for n,t in zip(novoUser,temp) if n != 0]
  tempNovoUser= [n for n in novoUser if n != 0]
  
  print(tempUser, tempNovoUser)

  #vamos usar a biblioteca scipy.stats que ja calcula o pearson!!!
  similarity[i] = stats.pearsonr(tempUser,tempNovoUser)[0] #a função retorna dois valores e o primeiro é o coefieciente de pearson
print()

print(similarity)

user: 0
Dados do usuário: [8 0 3 4 6]
[8, 3, 4] [8, 2, 3]
user: 1
Dados do usuário: [5 6 1 8 9]
[5, 1, 8] [8, 2, 3]
user: 2
Dados do usuário: [ 8  0  0  5 10]
[8, 0, 5] [8, 2, 3]

[0.9994237971287663, 0.236215438142997, 0.8723686098443353]


In [18]:
pesos_nota = np.zeros((3,5))
print(pesos_nota)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [20]:
pesos_nota = np.zeros((3,5))

for nUser in range(3):
  for nFilme in range(5):
    #print('nota_peso[',nUser, '][',nFilme, '] = , nao_assistidos[',nFilme, '], * ,matrix[',nUser,'][',nFilme, '], * similarity[',nUser,']')
    print('nota_peso[',nUser, '][',nFilme, '] = ', nao_assistidos[nFilme], ' * ' ,matrix[nUser][nFilme], ' * ', similarity[nUser])
    pesos_nota[nUser][nFilme] = nao_assistidos[nFilme] * matrix[nUser][nFilme] * similarity[nUser]
    print(nao_assistidos[nFilme] * matrix[nUser][nFilme] * similarity[nUser])

print(pesos_nota)

nota_peso[ 0 ][ 0 ] =  0  *  8  *  0.9994237971287663
0.0
nota_peso[ 0 ][ 1 ] =  1  *  0  *  0.9994237971287663
0.0
nota_peso[ 0 ][ 2 ] =  0  *  3  *  0.9994237971287663
0.0
nota_peso[ 0 ][ 3 ] =  0  *  4  *  0.9994237971287663
0.0
nota_peso[ 0 ][ 4 ] =  1  *  6  *  0.9994237971287663
5.996542782772598
nota_peso[ 1 ][ 0 ] =  0  *  5  *  0.236215438142997
0.0
nota_peso[ 1 ][ 1 ] =  1  *  6  *  0.236215438142997
1.417292628857982
nota_peso[ 1 ][ 2 ] =  0  *  1  *  0.236215438142997
0.0
nota_peso[ 1 ][ 3 ] =  0  *  8  *  0.236215438142997
0.0
nota_peso[ 1 ][ 4 ] =  1  *  9  *  0.236215438142997
2.125938943286973
nota_peso[ 2 ][ 0 ] =  0  *  8  *  0.8723686098443353
0.0
nota_peso[ 2 ][ 1 ] =  1  *  0  *  0.8723686098443353
0.0
nota_peso[ 2 ][ 2 ] =  0  *  0  *  0.8723686098443353
0.0
nota_peso[ 2 ][ 3 ] =  0  *  5  *  0.8723686098443353
0.0
nota_peso[ 2 ][ 4 ] =  1  *  10  *  0.8723686098443353
8.723686098443352
[[0.         0.         0.         0.         5.99654278]
 [0.         1.41729

In [22]:
notas_acumuladas = np.sum(pesos_nota.T,axis=1)
print(notas_acumuladas)

[ 0.          1.41729263  0.          0.         16.84616782]


In [29]:
temp_peso = pesos_nota
temp_peso[pesos_nota > 0] = 1
print(temp_peso)

temp_similaridade = np.zeros((3,5))


for nUser in range(3):
  for nFilme in range(5):
    temp_similaridade[nUser][nFilme] = temp_peso[nUser][nFilme] * similarity[nUser]

print('\n')
print(temp_similaridade)

print('\n')
similaridade_acumulada = np.sum(temp_similaridade.T,axis=1)
print(similaridade_acumulada)

[[0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 1.]
 [0. 0. 0. 0. 1.]]


[[0.         0.         0.         0.         0.9994238 ]
 [0.         0.23621544 0.         0.         0.23621544]
 [0.         0.         0.         0.         0.87236861]]


[0.         0.23621544 0.         0.         2.10800785]


In [30]:
nota_final =[0] * 5

#agora a normalização para cada filme com nota acumulada, eu normalizo pela soma dos pesos (similaridade)
for nFilme in range(5):
  if(similaridade_acumulada[nFilme] > 0):
    nota_final[nFilme] =  notas_acumuladas[nFilme] / similaridade_acumulada[nFilme]
    print(notas_acumuladas[nFilme] / similaridade_acumulada[nFilme])
  else:
    nota_final[nFilme] = 0

print(nota_final)

5.999999999999999
7.991510972567143
[0, 5.999999999999999, 0, 0, 7.991510972567143]


In [37]:
nAssistidos = sum(nao_assistidos)

notasOrdenadasIndex = sorted(range(len(nota_final)),key=nota_final.__getitem__)[::-1][0:nAssistidos]
print(notasOrdenadasIndex)

for i in notasOrdenadasIndex:
  print(nome_filmes[i], 'nota: ', nota_final[i])

[4, 1]
La Casa de Papel nota:  7.991510972567143
A Invocação do Mal nota:  5.999999999999999


In [36]:
nAssistidos = sum(nao_assistidos)
print(nAssistidos)

sorted(range(len(nota_final)),key=nota_final.__getitem__)[::-1][0:nAssistidos]

2


[4, 1]